# Form implementation generated from reading ui file 'pdf_editor_Qt.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QFileDialog 
from pdf_editor import fixed_split_pdf, ranged_split_pdf

class Ui_MainWindow(object):
    def __init__(self):
        self.path = ''
        super().__init__()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(476, 336)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.split_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.split_button.setGeometry(QtCore.QRect(320, 260, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Caladea")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.split_button.setFont(font)
        self.split_button.setObjectName("split_button")
        self.select_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.select_button.setGeometry(QtCore.QRect(320, 30, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Caladea")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.select_button.setFont(font)
        self.select_button.setObjectName("select_button")
        self.file_path = QtWidgets.QLabel(parent=self.centralwidget)
        self.file_path.setGeometry(QtCore.QRect(20, 30, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Caladea")
        font.setPointSize(12)
        self.file_path.setFont(font)
        self.file_path.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.file_path.setObjectName("file_path")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(100, 150, 121, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(330, 150, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Caladea")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.sample = QtWidgets.QLabel(parent=self.centralwidget)
        self.sample.setGeometry(QtCore.QRect(20, 240, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Caladea")
        font.setPointSize(12)
        self.sample.setFont(font)
        self.sample.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sample.setObjectName("sample")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        #setting Event 
        self.select_button.clicked.connect(self.selectFile)
        self.comboBox.currentIndexChanged.connect(self.selectComboBox)
        self.split_button.clicked.connect(self.splitFile)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PDF-Editor"))
        self.split_button.setText(_translate("MainWindow", "Split File"))
        self.select_button.setText(_translate("MainWindow", "Select File"))
        self.file_path.setText(_translate("MainWindow", ""))
        self.comboBox.setItemText(0, _translate("MainWindow", "固定頁數裁切"))
        self.comboBox.setItemText(1, _translate("MainWindow", "範圍裁切"))
        self.sample.setText(_translate("MainWindow", "e.g. 輸入2 -> pdf 每 2 頁存成新的pdf"))

    def selectFile(self):
        # 彈出文件選擇對話框，讓用戶選擇文件
        file, _ = QFileDialog.getOpenFileName(None, "Select PDF File", "", "PDF Files (*.pdf)")
        
        # 如果選擇了文件，更新 file_path 的文本顯示選擇的文件路徑
        if file:
            self.file_path.setText(file.split('/')[-1])
            self.path = file
    
    def selectComboBox(self):
        selected_text = self.comboBox.currentText()
        if selected_text == "固定頁數裁切":
            self.sample.setText("e.g. 輸入2 -> pdf 每 2 頁存成新的pdf")
        if selected_text == "範圍裁切":
            self.sample.setText("e.g. 輸入2-5 -> 將2到5頁存成新的pdf")

    def splitFile(self):
        selected_text = self.comboBox.currentText()
        if selected_text == "固定頁數裁切":
            page = int(self.lineEdit.text())
            fixed_split_pdf(self.path, f"{self.path.split("/")[-1].split(".")[0]}", page)
        if selected_text == "範圍裁切":
            ranged = self.lineEdit.text().split("-")
            ranged_split_pdf(self.path, f"{self.path.split("/")[-1].split(".")[0]}", int(ranged[0]), int(ranged[1]))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
